CREATE DATABASE FahrbareUntersaetze;

USE FahrbareUntersaetze;

CREATE TABLE Board_Art
(
ID INT NOT NULL AUTO_INCREMENT,
BoardART VARCHAR(35) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE Schrauben
(
ID INT NOT NULL AUTO_INCREMENT,
SchraubenTYPEN VARCHAR(15) NOT NULL,
SchraubenPREIS INT NOT NULL,
SchraubenHERSTELLER VARCHAR(40) DEFAULT 'unbekannt',
PRIMARY KEY(ID)
);

CREATE TABLE Muttern
(
ID INT NOT NULL AUTO_INCREMENT,
MutterTYP VARCHAR(15) NOT NULL,
MutterPREIS INT NOT NULL,
MutterHERSTELLER VARCHAR(40) DEFAULT 'unbekannt',
PRIMARY KEY(ID)
);

CREATE TABLE Achsen
(
ID INT NOT NULL AUTO_INCREMENT,
AchsenTYP VARCHAR(30) NOT NULL,
AchsenPREIS INT NOT NULL,
AchsenHERSTELLER VARCHAR(40) DEFAULT 'unbekannt',
PRIMARY KEY(ID)
);

CREATE TABLE Raeder
(
ID INT NOT NULL AUTO_INCREMENT,
RaederMATERIAL VARCHAR(30) NOT NULL,
RaederPREIS INT NOT NULL,
RaederHERSTELLER VARCHAR(40) DEFAULT 'unbekannt',
PRIMARY KEY(ID)
);

CREATE TABLE Kugellager
(
ID INT NOT NULL AUTO_INCREMENT, /*eS GIBT KEIN iDENTITY*/
KugellagerTYP VARCHAR(15) NOT NULL,
KugellagerPREIS INT NOT NULL,
KugellagerHERSTELLER VARCHAR(40) DEFAULT 'unbekannt',
PRIMARY KEY(ID)
);

CREATE TABLE Griptape
(
ID INT NOT NULL AUTO_INCREMENT,
GriptapeMATERIAL VARCHAR(20) NOT NULL,
GriptapePREIS INT NOT NULL,
GriptapeHERSTELLER VARCHAR(40) DEFAULT 'unbekannt',
PRIMARY KEY(ID)
);

CREATE TABLE Brett
(
ID INT NOT NULL AUTO_INCREMENT,
BrettMATERIAL VARCHAR(15) NOT NULL,
BrettPREIS INT NOT NULL,
BrettHERSTELLER VARCHAR(40) DEFAULT 'unbekannt',
PRIMARY KEY(ID)
);
